# Text Colors
black='\e[30m'
blue='\e[34m'
cyan='\e[36m'
grey='\e[30;1m'
green='\e[32m'
magenta='\e[35m'
red='\e[31m'
white='\e[37m'
yellow='\e[33m'
#RGB='\e[38;2;0;0;0m' #0;0;0=R;G;B
#Index='\e[38;5;0m'

# Background Colors
bblack='\e[40m'
bblue='\e[44m'
bcyan='\e[46m'
bgrey='\e[40;1m'
bgreen='\e[42m'
bmagenta='\e[45m'
bred='\e[41m'
bwhite='\e[47m'
byellow='\e[43m'
#bRGB='\e[48;2;0;0;0m' #0;0;0=R;G;B
#bIndex='\e[48;5;0m

reset='\e[0m'

