#!/bin/bash
sudo apt-get update
sudo apt-get install   $1 $2 $3
sudo apt-get build-dep $1 $2 3$
sudo apt-get upgrade      -y
sudo apt-get dist-upgrade -y
sudo apt-get autoremove   -y
sudo apt-get install      -f
